WIP: Validation for signup page
FACK1/GBMQ pull request #126
Opened 2019-04-08 12:46 UTC by RazanTayyem

2019-04-08 12:51 UTC, ameentalahmeh reviewed
good :+1:

2019-04-08 12:55 UTC, mhmdtshref requested changes
Try to use `sequelize` validations, if there are no validations using sequelize use `Joi`
Also, the validation function should be in the `src/validations` folder files.

2019-04-11 06:14 UTC, mhmdtshref commented on src/models/Student.model.js
> +      defaultValue: false,
I don't think that you need to set a default value if `allowNull` is false! Remove it from all these fields.

2019-04-11 07:46 UTC, ghassanmas requested changes
Password length could be less than 6

2019-04-11 08:09 UTC, ghassanmas approved these changes

2019-04-11 08:09 UTC, merged