WIP: File structure - Frontend
FACK1/GBMQ pull request #33
Opened 2019-03-20 10:44 UTC by RazanTayyem

```
  |__ public
  |     |__ index.html
  |    
  |__ src
  |     |__ app.js
  |     |__ index.js
  |     |__ components    
  |             |__ Button
  |             |      |__ index.js
  |             |      |__ index.css
  |             |
  |             |__ Form
  |             |      |__ index.js
  |             |      |__ index.css
  |             |
  |             |
  |             |__  Quiz
  |             |      |__ index.js
  |             |      |__ index.css
  |             |
  |             |__ Question
  |             |      |__ index.js
  |             |      |__ index.css
  |             |
  |             |__ Choice
  |             |      |__ index.js
  |             |      |__ index.css
  |             |
  |             |__ Image
  |             |      |__ index.js
  |             |      |__ index.css
  |             |
  |             |__ Pages
  |                     |                 
  |                     |__  Login 
  |                     |          |__ index.js
  |                     |          |__ index.css
  |                     |
  |                     |__ Signup 
  |                     |           |__ index.js
  |                     |           |__ index.css
  |                     |
  |                     |__  Start
  |                     |           |__ index.js
  |                     |           |__ index.css
  |                     |
  |                     |__  Result
  |                     |           |__ index.js
  |                     |           |__ index.css
  |                     |
  |                     |__   Activities
  |                     |           |__ index.js
  |                     |           |__ index.css
  |                     |
  |                     |__   Comparison
  |                                 |__ index.js
  |                                 |__ index.css
  |         
  |__ .eslintrc
  |__ .babelrc
  |__ .gitignore
  |__ package.json
  |__ package-lock.json
```

2019-03-20 13:35 UTC, ameentalahmeh approved these changes
seen :+1:

2019-03-21 06:43 UTC, mhmdtshref commented on student/package.json
> +  "name": "client",
Change this to `student`

2019-03-21 06:45 UTC, mhmdtshref requested changes
I think we'll use styled component, so rename the `index.css` files in the components folders to `index.style.js`.

2019-03-21 07:08 UTC, ghassanmas commented on student/README.md
> +This section has moved here: https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify
No need for this auto generated file

2019-03-21 07:39 UTC, ghassanmas requested changes
just add proxy to the pacakge.json

2019-03-21 07:49 UTC, merged