WIP: Form component
FACK1/GBMQ pull request #41
Opened 2019-03-21 19:42 UTC by RazanTayyem

2019-03-24 13:44 UTC, ameentalahmeh approved these changes
seen with @mhmdtshref  :+1:

2019-03-24 13:49 UTC, mhmdtshref requested changes

2019-03-24 13:49 UTC, mhmdtshref commented on student/package.json
>      "parcel": "^1.12.3",
We don't need parcel anymore!
Remove it!

2019-03-24 13:49 UTC, mhmdtshref commented on student/src/components/Button/index.style.js
> +width: 198px;
We shouldn't use static width for elements, use `vw` instead.

2019-03-24 13:49 UTC, mhmdtshref commented on student/src/components/Button/index.style.js
> +height: 44px;
Use `vw` here also!
It depends on the width

2019-03-24 13:49 UTC, mhmdtshref commented on student/src/components/Form/index.js
> +  updateDatesState = (name, value) => {
Remove All the date-related functions!

2019-03-24 13:49 UTC, mhmdtshref commented on student/src/components/Form/index.js
> +      .action({ ...fullValues, ...this.state.dateFieldsValues })
Remove date-related options

2019-03-24 18:46 UTC, RazanTayyem commented on student/src/components/Form/index.js
> +  updateDatesState = (name, value) => {
:joy_cat:

2019-03-25 08:28 UTC, mhmdtshref commented on student/src/components/Form/index.js
> +    this.state={};
Remove the state if you'll not use it

2019-03-25 08:29 UTC, mhmdtshref commented on student/src/components/Form/index.js
> +      .action({ ...fullValues,})
Here you need to type
`.action(fullValues)`

2019-03-25 08:31 UTC, mhmdtshref requested changes
View my comments

2019-03-25 12:01 UTC, ghassanmas approved these changes

2019-03-25 12:01 UTC, merged