WIP: Sign up
FACK1/GBMQ pull request #66
Opened 2019-03-31 11:00 UTC by RazanTayyem

2019-03-31 12:07 UTC, mhmdtshref commented on src/controllers/Student.controller.js
> +  bcrypt.hash(password, 10, (hashError, hashedPassword) => {
Use promises in the student function.
I mean, try to create separate functions to make the code clear.

2019-03-31 12:08 UTC, mhmdtshref requested changes
Use promises to clarify the code.

2019-04-01 06:53 UTC, ameentalahmeh commented
done :+1:

2019-04-01 06:59 UTC, ghassanmas approved these changes

2019-04-01 07:00 UTC, merged